### ISSUE TITLE
Coloring only a piece of characters in a cell

### ISSUE THREAD

**Issue by stla** [thebioengineer/colortable#29]
Hello,

  I discovered your package thanks to a comment to a [question](https://stackoverflow.com/q/68489214/1100107) of mine on Stackoverflow.
  I'm looking for a way to color only one word in a cell, not the entire cell. Do you envisage this feature for the future? 
  Or maybe you have a clue to help me?

Best regards.

**Comment by thebioengineer** [comment]
Hey, currently the code is expecting to color whole cells, thats correct. However, what you could do is create a color_vector with just the word function and style it with what you want and then paste the contents around it. 

Sounds like you kind of want syntax coloring?

**Comment by stla** [comment]
Thanks. I will try.

This is for my packages [findInFiles](https://github.com/stla/findInFiles#readme) and [findInGit](https://github.com/stla/findInGit#readme). On the gifs you can see, the results are displayed in HTML. But these packages also allow to return the results in a dataframe, and I'd like to color the matched pattern in the dataframe, as in the HTML.

**Comment by stla** [comment]
Hello,
  I've tried something but no luck. This does not work:

`paste0("f <-", color_vctr("function", text_color = "red"), "(x)")`

What do you mean by pasting around the color vector?

**Comment by stla** [comment]
This gives something interesting but there's a white space between the two components:

`c(color_vctr("function", text_color = "red"), color_vctr("(x)", text_color = "white"))`

**Comment by stla** [comment]
Not bad:
```
> cv <- c(color_vctr("function", text_color = "red"), color_vctr("(x)", text_color = "white"))
> cat(paste0(format(cv, method="console"), collapse = ""))
function(x) 
```

**Comment by stla** [comment]
Easier:
`cat(sub("function", format(color_vctr("function", text_color = "red")), "function(x)"))`

**Comment by stla** [comment]
I am able to get such a result but why the column name is not aligned ? 

![colortable](https://user-images.githubusercontent.com/4466543/127752150-b21261f1-ab3b-4942-af90-21e38416b418.png)

**Comment by stla** [comment]
That's fine. I've managed to do what I wanted with the help of the packages **vctrs**, **crayon** and **tibble**.
